name: 'Privado Scan'
description: 'Run a Privado scan'
inputs:
  upload:
    description: Whether to upload the scan to Privado Dashboard
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - run: echo "Will upload scan to dashboard -> ${{ github.event.inputs.upload }}"
      shell: bash
    - run: curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
      shell: bash
    - run: $HOME/.privado/bin/privado scan ${{ github.workspace }} --skip-upload
      shell: bash
    - run: $HOME/.privado/bin/privado upload ${{ github.workspace }}
      shell: bash
      if: ${{ github.event.inputs.upload == 'true' }}
